### ISSUE TITLE
Trouble running it with Cap 3 & ruby 2.1.1

### ISSUE THREAD

**Issue by ktaragorn** [javan/whenever#463]
Hi, I am having a lot of trouble running this on the above env..

Right now Im getting 

```
$ cap production whenever:update_crontab
cap aborted!
SyntaxError: /home/karthikt/.rvm/gems/ruby-2.1.1/gems/whenever-0.9.2/lib/whenever/tasks/whenever.rake:30: syntax error, unexpected keyword_end, expecting end-of-input
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/whenever-0.9.2/lib/whenever/capistrano.rb:4:in `load'
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/whenever-0.9.2/lib/whenever/capistrano.rb:4:in `<top (required)>'
config/deploy/production.rb:56:in `require'
config/deploy/production.rb:56:in `<top (required)>'
```

But earlier I got 

```
$ cap production whenever:update_crontab
DEBUG [df53860c] Running /usr/bin/env if test ! -d /home/ec2-user/<app>/current; then echo "Directory does not exist '/home/ec2-user/<app>/current'" 1>&2; false; fi on <app>
DEBUG [df53860c] Command: if test ! -d /home/ec2-user/<app>/current; then echo "Directory does not exist '/home/ec2-user/<app>/current'" 1>&2; false; fi
DEBUG [df53860c] Finished in 0.525 seconds with exit status 0 (successful).
cap aborted!
TypeError: no implicit conversion of nil into Hash
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/sshkit-1.4.0/lib/sshkit/backends/abstract.rb:88:in `merge'
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/sshkit-1.4.0/lib/sshkit/backends/abstract.rb:88:in `with'
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/whenever-0.9.2/lib/whenever/tasks/whenever.rake:8:in `block (2 levels) in setup_whenever_task'
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/sshkit-1.4.0/lib/sshkit/backends/abstract.rb:81:in `within'

```

And before that.. 

```
$ cap production whenever:update_crontab
cap aborted!
NoMethodError: undefined method `to_sym' for nil:NilClass
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/capistrano-3.2.1/lib/capistrano/configuration/servers/role_filter.rb:25:in `each'
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/capistrano-3.2.1/lib/capistrano/configuration/servers/role_filter.rb:25:in `flat_map'
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/capistrano-3.2.1/lib/capistrano/configuration/servers/role_filter.rb:25:in `required'
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/capistrano-3.2.1/lib/capistrano/configuration/servers/role_filter.rb:15:in `roles'
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/capistrano-3.2.1/lib/capistrano/configuration/servers/role_filter.rb:11:in `for'
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/capistrano-3.2.1/lib/capistrano/configuration/servers.rb:42:in `fetch_roles'
/home/karthikt/.rvm/gems/ruby-2.1.1/gems/capistrano-3.2.1/lib/capistrano/configuration/servers.rb:19:in `roles_for'
```

Changing the configuration around a bit changed the errors, but now its stuck in the latest one.

My `deploy/production.rb` has this

```
set :whenever_environment, "production"
set :whenever_command, "bundle exec whenever"
set :whenever_roles,        ->{ [:db, :app, :web] }
require "whenever/capistrano"
```

Adding `set :whenever_roles,        ->{ [:db, :app, :web] }` was what took me from the oldest error to the one after, while removing `set :whenever_command, "bundle exec whenever"` took me one step further..

**Comment by kremso** [comment]
In case anyone has the same issue and finds this: 

Make sure you are requiring whenenever/capistrano from Capfile, not from config/deploy.rb. Otherwise whenever's default values won't get loaded and weird errors like those above will ensue.

**Comment by rharriso** [comment]
Should the readme be updated?

**Comment by javan** [comment]
The README has always included the correct instructions: https://github.com/javan/whenever#capistrano-v3-integration

**Comment by rharriso** [comment]
Perhaps Capistrano 3 could be the default instruction set, since 2 hasn't
been updated in 2 years.

**Comment by oversee-ffleming** [comment]
It's also worth noting that Capistrano 3 doesn't have `defer`

**Comment by sergey-alekseev** [comment]
Thanks @kremso, that was exactly the reason.
