### ISSUE TITLE
Rails.env is not set on schedule.rb with Capistrano

### ISSUE THREAD

**Issue by micred** [javan/whenever#554]
Rails env is not set in any Capistrano task (RAILS_ENV is nil so the server use the default).

Based on that problem it's impossible to use Rails.env in my schedule.rb.
It's very useful to know the environment and do different stuff in staging or production environment.

One possibile solution:
adding `rails_env: fetch(:rails_env, fetch(:stage))` in the `with` block:

```
  def setup_whenever_task(*args, &block)
    args = Array(fetch(:whenever_command)) + args

    on roles fetch(:whenever_roles) do |host|
      args_for_host = block_given? ? args + Array(yield(host)) : args
      within release_path do
        with fetch(:whenever_command_environment_variables).merge(rails_env: fetch(:rails_env, fetch(:stage))) do
          execute *args_for_host
        end
      end
    end
  end

**Comment by karlingen** [comment]
:+1: also need this

**Comment by betesh** [comment]
Doesn't this accomplish the same thing?

    "before whenever:update_crontab", "deploy:set_rails_env"

Then, you can access the rails_env in your `config/schedule.rb` using `@set_variables[:environment]`

**Comment by micred** [comment]
I tried without success, Rails still loads with the development environment (yes, I know now I can get the environment from @set_variables[:environment] but if I use a gem that depends on environment (like https://github.com/laserlemon/figaro) it doesn't work.

With your tips ("deploy:set_rails_env") it executes:
```
INFO [51e8776e] Running ~/.rvm/bin/rvm 2.1.5 do bundle exec whenever --update-crontab base-backend_staging --set environment=staging --roles=web,app,db as deploy@xxxxx.com
DEBUG [51e8776e] Command: cd /home/deploy/apps/base-backend_staging/releases/20150827192821 && ~/.rvm/bin/rvm 2.1.5 do bundle exec whenever --update-crontab base-backend_staging --set environment=staging --roles=web,app,db
```

Editing whenever rake tast as on the first post it load Rails env correctly:
```
INFO [f2a0eaa1] Running ~/.rvm/bin/rvm 2.1.5 do bundle exec whenever --update-crontab base-backend_staging --set environment=staging --roles=web,app,db as deploy@xxxxx.com
DEBUG [f2a0eaa1] Command: cd /home/deploy/apps/base-backend_staging/releases/20150827193618 && ( RAILS_ENV=staging ~/.rvm/bin/rvm 2.1.5 do bundle exec whenever --update-crontab base-backend_staging --set environment=staging --roles=web,app,db )
```

**Comment by betesh** [comment]
so why not just add to the top of `config/schedule.rb`:

    ENV['RAILS_ENV'] = @set_variables[:environment]

**Comment by micred** [comment]
Because Rails has already been loaded

**Comment by david50407** [comment]
i've got the same problem, logs below:

```
INFO [3a2fc132] Running /usr/local/rvm/bin/rvm default do bundle exec whenever --update-crontab stampex-api --set environment=production --roles=app,web,db as deployer@xxx.xxx
DEBUG [3a2fc132] Command: cd ~/xxx/releases/20150911055113 && /usr/local/rvm/bin/rvm default do bundle exec whenever --update-crontab xxx-cron --set environment=production --roles=app,web,db
DEBUG [3a2fc132] 	/home/deployer/xxx/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection'
DEBUG [3a2fc132] 	:
DEBUG [3a2fc132] 	'development' database is not configured. Available: ["production"]
DEBUG [3a2fc132] 	 (
DEBUG [3a2fc132] 	ActiveRecord::AdapterNotSpecified
DEBUG [3a2fc132] 	)
```

I've already set `rails_env` to `production` in my deploy config, and the command also execute with `--set environment=production`.
BUT, my rails loaded with the environment `development` so the ActiveRecord throw the exception back to me.
I think the patch above (https://github.com/javan/whenever/pull/562) is necessary to solve this problem.

**Comment by betesh** [comment]
I'm very curious what your use case is.  if rails has already been loaded before config/schedule, where and how was it loaded?

**Comment by micred** [comment]
I think it was loaded in application.rb with `require 'rails/all'`.
@david50407 please do `export  | grep _ENV` and tell us if you have set RAILS_ENV/RACK_ENV

**Comment by betesh** [comment]
How does the command `/usr/local/rvm/bin/rvm default do bundle exec whenever` load any part of your rails application?  The only file from your project that it loads is `config/schedule.rb` and whatever is `require`d from there.

**Comment by galievruslan** [comment]
I have the same problem.   
shedule.rb:  
```
ENV['RAILS_ENV'] = @set_variables[:environment]
require File.expand_path(File.dirname(__FILE__) + "/environment")
setting = Setting.first

set :job_template, "bash -l -i -c ':job'"

set :output, "/var/log/cron.log"

if setting and setting.unload_orders
  every setting.upload_period.minutes do
    rake "exchange:send_orders_ftp"
  end
end

if setting and setting.unload_audit_documents
  every setting.upload_period.minutes do
    rake "exchange:send_audit_documents_ftp"
  end
end

if setting and setting.unload_refunds
  every setting.upload_period.minutes do
    rake "exchange:send_refunds_ftp"
  end
end
```

The error occurs when deploy with capistrano:   
```
  * executing "cd /var/www/mss/releases/20151003121604 && bundle exec whenever --update-crontab mss --set environment=production --roles db"
    servers: ["192.168.3.5"]
    [192.168.3.5] executing command
 ** [out :: 192.168.3.5] /var/www/mss/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:47:in `resolve_hash_connection'
 ** [out :: 192.168.3.5] :
 ** [out :: 192.168.3.5] database configuration does not specify adapter
 ** [out :: 192.168.3.5] (
 ** [out :: 192.168.3.5] ActiveRecord::AdapterNotSpecified
 ** [out :: 192.168.3.5] )
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:41:in `resolve_string_connection'
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:25:in `spec'
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in `establish_connection'
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activerecord-import-0.3.1/lib/activerecord-import.rb:4:in `establish_connection_with_activerecord_import'
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/railtie.rb:88:in `block (2 levels) in <class:Railtie>'
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:25:in `each'
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
 ** [out :: 192.168.3.5]
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/railtie.rb:80:in `block in <class:Railtie>'
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `instance_exec'
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `run'
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/initializable.rb:55:in `block in run_initializers'
 ** [out :: 192.168.3.5] from /var/www/mss/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `each'
```
As I understand it, he tries to find a development database. Settings which in my database.yml not.   
Is there a solution to this problem?

**Comment by betesh** [comment]
@galievruslan I don't think your conclusion is correct.  If it were trying to find a development database, and there was no development key in your database.yml, then you'd get the error message from [line 39 of connection_specification.rb](https://github.com/rails/rails/blob/v3.2.22/activerecord/lib/active_record/connection_adapters/abstract/connection_specification.rb#L39) (`"#{spec} database is not configured"`), but you're actually getting the error on line 41: `"database configuration does not specify adapter"`.

To debug, I would add `puts hash.inspect` after line 39.  My guess is that you'll find that it **is** using `production` and that the adapter is missing from the configuration there.

**Comment by galievruslan** [comment]
No, you're wrong. If my database.yml file config register setting for the database development will swear that the database development is not found.
Ie whenever it uses the default development environment when selecting data:
setting = Setting.first

This my database.yml :
```
production:
        adapter: postgis
        encoding: unicode
        pool: 5
        host: localhost
        database: mss
        username: mss
        password: ********
```

**Comment by betesh** [comment]
Strange, because that doesn't match the error message you're getting
