### ISSUE TITLE
Whenever failed to deploy due to uninitialized constant Whenever::Joblist::

### ISSUE THREAD

**Issue by mdere** [javan/whenever#566]
Hello! So before I get started on my issue, I reviewed this issue earlier https://github.com/javan/whenever/issues/81. I wasn't really sure if that was my answer. I am a relatively new rails developer and trying to wrap my whole head around deployment with capistrano and configuration with cronjobs.  So below is the log output from deploying my code to staging server. 

```
 * 2015-06-25 09:57:57 executing `whenever:update_crontab'
  * executing "cd /var/www/revv/current && bundle exec whenever --update-crontab 52.11.218.78 --set environment=staging"
    servers: ["52.11.218.78"]
    [52.11.218.78] executing command
 ** [out :: 52.11.218.78] config/schedule.rb:52:in `block in initialize'
 ** [out :: 52.11.218.78] :
 ** [out :: 52.11.218.78] uninitialized constant Whenever::JobList::Organization
 ** [out :: 52.11.218.78] (
 ** [out :: 52.11.218.78] NameError
 ** [out :: 52.11.218.78] )
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/gems/whenever-0.7.3/lib/whenever/job_list.rb:38:in `every'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from config/schedule.rb:51:in `initialize'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/gems/whenever-0.7.3/lib/whenever/job_list.rb:19:in `instance_eval'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/gems/whenever-0.7.3/lib/whenever/job_list.rb:19:in `initialize'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/gems/whenever-0.7.3/lib/whenever.rb:15:in `new'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/gems/whenever-0.7.3/lib/whenever.rb:15:in `cron'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/gems/whenever-0.7.3/lib/whenever/command_line.rb:55:in `whenever_cron'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/gems/whenever-0.7.3/lib/whenever/command_line.rb:105:in `updated_crontab'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/gems/whenever-0.7.3/lib/whenever/command_line.rb:36:in `run'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/gems/whenever-0.7.3/lib/whenever/command_line.rb:7:in `execute'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/gems/whenever-0.7.3/bin/whenever:38:in `<top (required)>'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/bin/whenever:23:in `load'
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] 
 ** [out :: 52.11.218.78] from /var/www/revv/shared/bundle/ruby/2.1.0/bin/whenever:23:in `<main>'
 ** [out :: 52.11.218.78] 
    command finished in 1373ms
failed: "rvm_path=$HOME/.rvm/ $HOME/.rvm/bin/rvm-shell 'ruby-2.1.2' -c 'cd /var/www/revv/current && bundle exec whenever --update-crontab 52.11.218.78 --set environment=staging'" on 52.11.218.78
```
deploy.rb
``` deploy.rb
require 'rvm/capistrano'
require 'capistrano/sidekiq'
require 'whenever/capistrano'
set :whenever_command, 'bundle exec whenever'
```
Versions:
``` 
mdere@mdere-VirtualBox ~ $ which gem
/home/mdere/.rvm/rubies/ruby-2.2.1/bin/gem
mdere@mdere-VirtualBox ~ $ gem -v
2.4.6
mdere@mdere-VirtualBox ~ $ which bundle
/home/mdere/.rvm/gems/ruby-2.2.1/bin/bundle
mdere@mdere-VirtualBox ~ $ bundle -v
Bundler version 1.8.5
```

I am using version 0.7.3, per recommendation from another thread and my deployment proceeded further compared to higher versions

Thank in advance!

**Comment by mdere** [comment]
Ah I think I understand my own issue, I can't call ruby code within my schedule.rb file as it does not recognize my model....

What would you recommend for me to do?

I wanted to do this:
```
every :day, at: '04:00 am' do
  Organization.all.each do |org|
    runner "UserConfirmer.perform_async(#{org.id})"
  end
end
```

Would I just need to build some rake task and have that logic be included there?

**Comment by AliSepehri** [comment]
Your string arg will be run as a ruby code line, so you don't need `#` character before your `org.id`, like below:
```
    runner "UserConfirmer.perform_async(org.id)"
```
