### ISSUE TITLE
cap aborted! NameError: instance variable @_env not defined for 0.9.6

### ISSUE THREAD

**Issue by wojtha** [javan/whenever#638]
After upgrade to whenever 0.9.6 I am getting the following error during deploy. Moving back to 0.9.4 resolves the issue.

```
cap aborted!
NameError: instance variable @_env not defined
/home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:91:in `remove_instance_variable'
/home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:91:in `with'
/home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/whenever-0.9.6/lib/whenever/capistrano/v3/tasks/whenever.rake:8:in `block (2 levels) in setup_whenever_task'
/home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:80:in `within'
/home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/whenever-0.9.6/lib/whenever/capistrano/v3/tasks/whenever.rake:7:in `block in setup_whenever_task'
/home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:29:in `run'
/home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.10.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => whenever:update_crontab
The deploy has failed with an error: instance variable @_env not defined
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```
Environment:
* ruby 2.3.1
* sshkit 1.10.0
* capistrano 3.5.0
* whenever 0.9.6

**Comment by benlangfeld** [comment]
This was already fixed. Please upgrade: https://github.com/javan/whenever/blob/master/CHANGELOG.md#097--june-14-2016
