### ISSUE TITLE
Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.

### ISSUE THREAD

**Issue by dwiyanr** [javan/whenever#681]
hi all
please help i got error in my log
```
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
Backtrace for gem load error is:
/home/dwiyan/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/home/dwiyan/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/home/dwiyan/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/home/dwiyan/.rvm/gems/ruby-2.3.0/gems/uglifier-3.0.0/lib/uglifier.rb:5:in `require'
/home/dwiyan/.rvm/gems/ruby-2.3.0/gems/uglifier-3.0.0/lib/uglifier.rb:5:in `<top (required)>'
/home/dwiyan/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.5/lib/bundler/runtime.rb:91:in `require'
/home/dwiyan/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.5/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/dwiyan/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.5/lib/bundler/runtime.rb:86:in `each'
...
```
my schedule.rb
```
set :output, 'log/cron_log.log'
# Run rake every 3 minutes between 6am to 20pm
every '*/1 6-20 * * *' do
  rake 'hosts:last_fetch'
end
```
i already installed my nodejs version `v6.2.2`
my rake task has been succesfully running in my terminal but it doesnt running using whenever

**Comment by benlangfeld** [comment]
You'll need to make sure node is available within the PATH that cron has access to. A little googling along those lines should lead you to a solution, but if you get stuck post again on the mailing list for help.

Best of luck :)
