### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by GarPit** [javan/whenever#701]
This happens on deploy with capistrano. Command generated by capistrano:

    Running /usr/local/rvm/bin/rvm 2.2.3 do bundle exec whenever --update-crontab santeh_opt --set environment=production --roles=app,web,db

Stacktrace:

    /opt/santeh_opt/shared/bundle/ruby/2.2.0/gems/whenever-0.9.7/lib/whenever/command_line.rb:115:in `split'
    /opt/santeh_opt/shared/bundle/ruby/2.2.0/gems/whenever-0.9.7/lib/whenever/command_line.rb:115:in `prepare'

**Comment by PuZZleDucK** [comment]
The code comments about `prepare` mention "Strip n lines from the top of the file as specified by the :cut option"

Have you set the cut option in your project?
