### ISSUE TITLE
Bad Integration with rvm

### ISSUE THREAD

**Issue by bpdarlyn** [javan/whenever#721]
I am using rvm with gemsets
now I have a file
```
~/.rvm and other ~/.rvmrc
```
then file content the rvmrc is :
```
rvm_trust_rvmrcs_flag=1
```
my file schedule.rb
``` ruby
env :PATH, ENV['PATH']
env :GEM_PATH, "/home/bpdarlyn/.rvm/wrappers/ruby-2.3.1@trackdio_web"
every '*/1 * * * *' do
    runner "Model.some_method"
end
```
but when I see the logs the cron this is the output with error
```
/home/bpdarlyn/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
	from /home/bpdarlyn/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:298:in `activate_bin_path'
	from /home/bpdarlyn/.rvm/gems/ruby-2.3.1@trackdio_web/bin/bundle:22:in `<main>'
	from /home/bpdarlyn/.rvm/gems/ruby-2.3.1@trackdio_web/bin/ruby_executable_hooks:15:in `eval'
	from /home/bpdarlyn/.rvm/gems/ruby-2.3.1@trackdio_web/bin/ruby_executable_hooks:15:in `<main>'
```
what do you thing than I am doing wrong ?

**Comment by bpdarlyn** [comment]
I solved my problema doing this :

``` ruby
ENV.each { |k, v| env(k, v) }
every '*/1 * * * *' do
    runner "Model.my_method"
end

```
