### ISSUE TITLE
Curly bracket block syntax is not working

### ISSUE THREAD

**Issue by ugultopu** [javan/whenever#752]
This works fine:

```
every :day do
  rake 'billing:daily'
end
```

However, this throws a syntax error:

`every :day { rake 'billing:daily' }`

```
~/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/whenever-0.10.0/lib/whenever/job_list.rb:25:in `instance_eval': config/schedule.rb:26: syntax error, unexpected '{', expecting end-of-input (SyntaxError)
every :day { rake 'billing:daily' }
            ^
	from ~/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/whenever-0.10.0/lib/whenever/job_list.rb:25:in `initialize'
	from ~/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/whenever-0.10.0/lib/whenever.rb:12:in `new'
	from ~/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/whenever-0.10.0/lib/whenever.rb:12:in `cron'
	from ~/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:42:in `run'
	from ~/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:6:in `execute'
	from ~/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/whenever-0.10.0/bin/whenever:44:in `<top (required)>'
	from ~/.rbenv/versions/2.4.3/bin/whenever:23:in `load'
	from ~/.rbenv/versions/2.4.3/bin/whenever:23:in `<main>'
```

Aren't these two the same thing? Why isn't the latter one not working?

**Comment by benlangfeld** [comment]
You need parens around the argument. This is a basic ruby thing, not specific to Whenever.
