### ISSUE TITLE
Calling via Capistrano3 fails

### ISSUE THREAD

**Issue by ryanbooker** [javan/whenever#765]
When called via cap whenever fails with this error.
```
NameError: uninitialized constant #<Class:#<Whenever::JobList:0x00005623cba8abe8>>::Rails
  config/schedule.rb:23:in `initialize'
  /var/www/myapp/shared/bundle/ruby/2.5.0/gems/whenever-0.10.0/lib/whenever/job_list.rb:25:in `instance_eval'
  /var/www/myapp/shared/bundle/ruby/2.5.0/gems/whenever-0.10.0/lib/whenever/job_list.rb:25:in `initialize'
  /var/www/myapp/shared/bundle/ruby/2.5.0/gems/whenever-0.10.0/lib/whenever.rb:12:in `new'
  /var/www/myapp/shared/bundle/ruby/2.5.0/gems/whenever-0.10.0/lib/whenever.rb:12:in `cron'
  /var/www/myapp/shared/bundle/ruby/2.5.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:57:in `whenever_cron'
  /var/www/myapp/shared/bundle/ruby/2.5.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:111:in `updated_crontab'
  /var/www/myapp/shared/bundle/ruby/2.5.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:38:in `run'
  /var/www/myapp/shared/bundle/ruby/2.5.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:6:in `execute'
  /var/www/myapp/shared/bundle/ruby/2.5.0/gems/whenever-0.10.0/bin/whenever:44:in `<top (required)>'
  /var/www/myapp/shared/bundle/ruby/2.5.0/bin/whenever:23:in `load'
  /var/www/myapp/shared/bundle/ruby/2.5.0/bin/whenever:23:in `<top (required)>'
bundle stderr: Nothing written
(Backtrace restricted to imported tasks)
cap aborted!
```

**Comment by benlangfeld** [comment]
That’s a reference to your schedule, where you are using `Rails`. This doesn’t seem like a Whenever bug.

**Comment by ryanbooker** [comment]
I take it from that response, I can't access Rails settings. Ok. Thanks.
