### ISSUE TITLE
Operation not permitted - getcwd (Errno::EPERM)

### ISSUE THREAD

**Issue by julio336** [javan/whenever#825]
After a simple test with the basic Setup I got this error:

`Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:54:in `pwd': Operation not permitted - getcwd (Errno::EPERM)
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:54:in `lockfile_contents'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:41:in `lockfile_version'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:10:in `bundler_version'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:17:in `block in prioritize!'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:17:in `find_index'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:17:in `prioritize!'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/dependency.rb:280:in `matching_specs'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems.rb:257:in `find_spec_for_exe'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems.rb:284:in `activate_bin_path'
    from /Users/<username>/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'`

I'm not sure if there is an issue of the gem or another thing.

**Comment by julio336** [comment]
But there is a problem with the gem working with Macbook M1, do you have any guide to make the gem functional?

**Comment by frenkel** [comment]
This is not an issue with this gem, because only files of ruby/bundler are listed in the backtrace.
