### ISSUE TITLE
ActionView::Template::Error (undefined method `>' for nil:NilClass):

### ISSUE THREAD

**Issue by baranyeni** [javan/whenever#829]
Hi, I am trying to run a rake task every Monday ay 06:00. But getting the following error on my browser when I add a cron task with following configuration. 

```
every '0 6 * * 1' do
  rake 'namespace:taskname'
end
```

This is What I've got in ruby console, 
```
ActionView::Template::Error (undefined method `>' for nil:NilClass):
    18:       <% job_list.each_with_index do |job, i| %>
    19:       <tr>
    20:         <td><%= job.description %></td>
    21:         <td><%= job.interval %></td>
    22:         <td><%= job.at %></td>
    23:         <td><%= job.roles %></td>
    24:         <td><%= link_to t('whenever.run_now'), run_job_path(i), class: 'btn btn-danger', title: job.output %></td>
  actionview (4.2.11.3) lib/action_view/helpers/date_helper.rb:78:in `distance_of_time_in_words'
  whenever-web (0.0.5) app/models/whenever/web_job.rb:24:in `interval'
```

Here is the screenshot of `/whenever`
![Screenshot 2022-11-24 at 02 21 09](https://user-images.githubusercontent.com/46084338/203662444-5a1b052a-c7bc-4c02-9e1b-362098b003d0.png)

**Comment by baranyeni** [comment]
I've fixed it with changing `'0 6 * * 1'` to `'0 06 * * 1'`. I don't know why but gem do not allow the first notation. As I've checked from crontab.guru both are pointing same schedule. Hope this helps to someone else.
